---
- hosts: devserver
    become: yes
    ignore_errors: yes
     tasks: 
- name: install package
  package:
   name: "{{ item }}"
   state: present
 with_items:
   - wget
   - samba
   - java-8*
   - finger  
